apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.chatbotapi.name }}
  name: {{ .Values.chatbotapi.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.chatbotapi.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.chatbotapi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.chatbotapi.name }}
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: chatbotapi-secret
        image: {{ .Values.global.aws_account_id }}.dkr.ecr.ap-southeast-1.amazonaws.com/{{ .Values.chatbotapi.image }}:{{ .Values.chatbotapi.image_tag }}
        name: {{ .Values.chatbotapi.name }}
        ports:
        - containerPort: {{ .Values.chatbotapi.containerPort }}
        volumeMounts:
        - mountPath: /home/node/app/volume/chatbot
          subPath: chatbot
          name: chatbotapi-pv
      restartPolicy: Always
      volumes:
      - name: chatbotapi-pv
        persistentVolumeClaim:
          claimName: efs-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.chatbotapi.name }}
  name: {{ .Values.chatbotapi.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: {{ .Values.chatbotapi.port }}
    targetPort: {{ .Values.chatbotapi.targetPort }}
  selector:
    app: {{ .Values.chatbotapi.name }}
              

---

apiVersion: v1
type: Opaque
data:
  MAMONGO_HOST: {{ .Values.database.database_url }}
  MASQL_HOST: {{ .Values.database.database_url }}
  MYSQL_DATABASE: {{ .Values.database.database_name }}
  MYSQL_PASSWORD: {{ .Values.database.database_pass }}
  MYSQL_USER: {{ .Values.database.database_user }}
  NODE_ENV: {{ .Values.global.namespace }}
  jwtSecret: {{ .Values.env.jwtSecret }}
  PORT: {{ .Values.env.port }}
kind: Secret
metadata:
  name: chatbotapi-secret


