apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.chatboxui.name }}
  name: {{ .Values.chatboxui.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.chatboxui.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.chatboxui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.chatboxui.name }}
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: chatboxui-secret
        image: {{ .Values.global.aws_account_id }}.dkr.ecr.ap-southeast-1.amazonaws.com/{{ .Values.chatboxui.image }}:{{ .Values.chatboxui.image_tag }}
        name: {{ .Values.chatboxui.name }}
        ports:
        - containerPort: {{ .Values.chatboxui.containerPort }}
      restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.chatboxui.name }}
  name: {{ .Values.chatboxui.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: {{ .Values.chatboxui.port }}
    targetPort: {{ .Values.chatboxui.targetPort }}
  selector:
    app: {{ .Values.chatboxui.name }}
              


---

apiVersion: v1
type: Opaque
data:
  MAMONGO_HOST: {{ .Values.database.database_url }}
  MASQL_HOST: {{ .Values.database.database_url }}
  MYSQL_DATABASE: {{ .Values.database.database_name }}
  MYSQL_PASSWORD: {{ .Values.database.database_pass }}
  MYSQL_USER: {{ .Values.database.database_user }}
  NODE_ENV: {{ .Values.env.namespace }}
  jwtSecret: {{ .Values.env.jwtSecret }}
kind: Secret
metadata:
  name: chatboxui-secret

