apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.userapi.name }}
  name: {{ .Values.userapi.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.userapi.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.userapi.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.userapi.name }}
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: userapi-secret
        env:
        - name: confidentLevel
          value: '0.100'
        - name: cycle
          value: '100'
        - name: mode
          value: AFM
        image: "{{ .Values.global.aws_account_id }}.dkr.ecr.ap-southeast-1.amazonaws.com/{{ .Values.chatbotapi.image }}:{{ .Values.chatbotapi.image_tag }}"
        name: {{ .Values.userapi.name }}
        volumeMounts:
        - mountPath: /home/node/app/volume/userapi
          subPath: chatbot
          name: userapi-pv
      restartPolicy: Always
      volumes:
      - name: userapi-pv
        persistentVolumeClaim:
          claimName: efs-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.userapi.name }}
  name: {{ .Values.userapi.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.userapi.port }}
    targetPort: {{ .Values.userapi.targetPort }}
  selector:
    app: {{ .Values.userapi.name }}


---

apiVersion: v1
data:
  MAMONGO_HOST: {{ .Values.database.database_url }}
  MASQL_HOST: {{ .Values.database.database_url }}
  MYSQL_DATABASE: {{ .Values.database.database_name }}
  MYSQL_PASSWORD: {{ .Values.database.database_pass }}
  MYSQL_USER: {{ .Values.database.database_user }}
  NODE_ENV: {{ .Values.global.namespace }}
  jwtSecret: {{ .Values.env.jwtSecret }}
kind: Secret
type: Opaque
metadata:
  name: userapi-secret
              




